apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: default
  labels:
    app.kubernetes.io/name: homepage
data:
  proxmox.yaml: ""
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    title: My Homepage
    description: Welcome to my homepage
    background: 
      image: https://images.unsplash.com/photo-1490806843957-31f4c9a91c65?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D
      opacity: 80
      blur: sm
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/
              icon: github.png
        - Cloudflare:
            - abbr: CF
              href: https://dash.cloudflare.com/
              icon: cloudflare.png
        - PA domain access:
            - abbr: PA
              href: https://access.pavietnam.vn
        - Claude:
            - abbr: CL
              href: https://claude.ai/
              icon: sh-claude.svg
    - Social:
        - Facebook:
            - abbr: FB
              href: https://facebook.com/
              icon: facebook.png
        - Twitter:
            - abbr: TW
              href: https://twitter.com/
              icon: twitter.png
        - LinkedIn:
            - abbr: LI
              href: https://linkedin.com/
              icon: linkedin.png
    - Entertainment:
        - YouTube:
            - abbr: YT
              href: https://youtube.com/
              icon: youtube.png
        - Spotify:
            - abbr: SP
              href: https://spotify.com/
              icon: spotify.png
  services.yaml: |
    - Infrastructure:
        - Proxmox VE:
            href: https://proxmox.nguyenvietkhoi.io.vn:8006/
            description: Promox 
            icon: proxmox.png
            siteMonitor: https://proxmox.nguyenvietkhoi.io.vn:8006/

    -  Network:
        - OPNsense:
            href: https://opnsense.nguyenvietkhoi.io.vn/
            description: OPNsense router
            icon: opnsense.png
            siteMonitor: https://opnsense.nguyenvietkhoi.io.vn/

        - Omada Controller:
            href: https://omada.nguyenvietkhoi.io.vn/
            description: Omada Controller
            icon: sh-omada.svg
            siteMonitor: https://omada.nguyenvietkhoi.io.vn/
    - Storage:
        - Longhorn:
            href: https://longhorn.nguyenvietkhoi.io.vn/
            description: Storage management for Kubernetes
            icon: longhorn.png
            siteMonitor: https://longhorn.nguyenvietkhoi.io.vn/
  widgets.yaml: |
    - search:
        provider: google
        target: _blank
  docker.yaml: ""