apiVersion: apps/v1
kind: Deployment
metadata:
  name: karakeep
  namespace: karakeep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: karakeep
  template:
    metadata:
      labels:
        app: karakeep
    spec:
      containers:
        - name: karakeep
          image: ghcr.io/karakeep-app/karakeep:release
          ports:
            - containerPort: 3000
          env:
            - name: NEXTAUTH_URL
              value: "https://karakeep.nguyenvietkhoi.io.vn"
            - name: NEXTAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: karakeep-secret
                  key: NEXTAUTH_SECRET
            - name: MEILI_ADDR
              value: "http://meilisearch:7700"
            - name: MEILI_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: karakeep-secret
                  key: MEILI_MASTER_KEY
            - name: DISABLE_SIGNUPS
              value: "true"
            - name: BROWSER_WEB_URL
              value: "http://chromium:3000"
            - name: DATA_DIR
              value: /data
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: karakeep-data